### ISSUE TITLE
Provide Doxygen documentation

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/matio-cpp#27]
I've seen that the code has been documented in such a way the doxygen can be generated. It would be really nice to provide it 

cc @isorrentino @S-Dafarra

**Comment by S-Dafarra** [comment]
I have some preliminary results in the branch [``gh-pages``](https://github.com/dic-iit/matio-cpp/tree/gh-pages). Then, I am wondering the following:
- how can I have Github storing the documentation online?
- how can I trigger the generation of the documentation every time we create a new release?

I don't know if this action can help: https://github.com/marketplace/actions/doxygen-action

cc @traversaro

**Comment by GiulioRomualdi** [comment]
Hi @S-Dafarra 

> how can I have Github storing the documentation online?

https://github.com/robotology/how-to-document-modules

> how can I trigger the generation of the documentation every time we create a new release?

You can Please check here: https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/.github/workflows/gh-pages.yml
and here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

**Comment by S-Dafarra** [comment]
Thanks @GiulioRomualdi for the pointers, they were extremely useful.

I have added the link to the documentation on the homepage. It should be automatically updated at every new release.

Closing.
