### ISSUE TITLE
Failed FileUnitTests

### ISSUE THREAD

**Issue by DrasLorus** [dic-iit/matio-cpp#28]
## Problem

After a clean build, 10 of the tests pass, and the 8th (FileUnitTests) constantly fails.

## Environment

* Archlinux Rolling
* kernel 5.10.10
* MatIO 1.5.19
* CMake 3.19.3
* GNU Make 4.3 
* GCC 10.2.0
* Catch2 2.13.3

## Steps

It has been tested to remove code blocks between `[]`. Code between `<|>` have all been tested independently.

    git clone https://github.com/dic-iit/matio-cpp.git && cd matio-cpp
    cmake -B build . -DBUILD_TESTING=ON [-DCMAKE_BUILD_TYPE=<None|Release|Debug>]
    cd build
    make [-j]
    ctest -V

## Results

Every tests pass except the 8th which fail with:

[ctest.log](https://github.com/dic-iit/matio-cpp/files/5879184/ctest.log)

It seems only related to strings so it may not impact the remains of the library.
Do you know from where it could originate? Can it be a problem from Matio (since it seems problems with strings exist)?

**Comment by GiulioRomualdi** [comment]
Cc @S-Dafarra and @traversaro

**Comment by S-Dafarra** [comment]
Hi @DrasLorus, thanks for reporting this issue.
From the log, the relevant lines are 
```
8: /home/moniere/build/matio-cpp/src/libmatio-cpp/test/FileUnitTest.cpp:267: FAILED:
8:   REQUIRE( file.read("string").asString()() == "test" )
8: with expansion:
8:   "t
8: e
8: " == "test"
```
The corresponding lines that fail are https://github.com/dic-iit/matio-cpp/blob/ef999d85b8c2a5cf7f3406ffed951437536e5d40/test/FileUnitTest.cpp#L159-L161

Just to check, can you load https://github.com/dic-iit/matio-cpp/blob/ef999d85b8c2a5cf7f3406ffed951437536e5d40/test/input.mat with Matlab or Octave and check if the variable named "string" is equal to "test"?

**Comment by DrasLorus** [comment]
Hi @S-Dafarra,

Just tested ; Either Octave (v6.1.0) or MATLAB (R2019b) report that `string` in `input.mat` is an array of 4 characters, and equals to `'test'`.
It seems that it's related to the matioCpp or at least to MatIO :confused: . But I hadn't encounter this in plain MatIO (yet).

**Comment by traversaro** [comment]
It is possible that we need to change the line:
~~~
 REQUIRE(string() == "test"); 
~~~
to properly convert the string (an instance of matioCpp::string) variable to `std::string`? Because I am not sure what method is called for `string()` ?

**Comment by traversaro** [comment]
> The corresponding lines that fail are

I guess the lines are https://github.com/dic-iit/matio-cpp/blob/ef999d85b8c2a5cf7f3406ffed951437536e5d40/test/FileUnitTest.cpp#L267 .

**Comment by S-Dafarra** [comment]
The code that converts the variable to a string is https://github.com/dic-iit/matio-cpp/blob/ef999d85b8c2a5cf7f3406ffed951437536e5d40/include/matioCpp/impl/Vector.tpp#L276-L281

The method ``data()`` casts the ``data`` field of the internal ``matvar_t`` variable to a ``char*``, while ``size`` takes the maximum between the first two dimensions of the ``matvar_t`` variable. Since the string seems to be corrupted, I would guess that the cast to ``char*`` is the problem.

**Comment by traversaro** [comment]
If the problem is related to the use of matio 1.15.19, it may be possible to reproduce it also on a Ubuntu computer by using conda-forge that uses it, while Ubuntu 20.04 uses 1.15.17. @S-Dafarra or @GiulioRomualdi if you are interested in doing this I can write a few instructions on how to do so.

**Comment by S-Dafarra** [comment]
> If the problem is related to the use of matio 1.15.19, it may be possible to reproduce it also on a Ubuntu computer by using conda-forge that uses it, while Ubuntu 20.04 uses 1.15.17. @S-Dafarra or @GiulioRomualdi if you are interested in doing this I can write a few instructions on how to do so.

That would great @traversaro, thanks.

@DrasLorus, just for debug, can I ask you to add the following lines
```
    std::string classType, dataType;
    matioCpp::get_types_names_from_matvart(input.read("string").toMatio(), classType, dataType);
    std::cerr << "String class type: " << classType <<std::endl;
    std::cerr << "String data type: " << dataType <<std::endl;
```
after line 161 of ``FileUnitTest.cpp`` and provide the output?

On my machine I get 
```
String class type: CHAR
String value type: UTF8
```

**Comment by DrasLorus** [comment]
Okay, it may be linked to the test? I tried to reproduce it outside of the test framework and I encountered no error.
With the following code:
[quick_test.txt](https://github.com/dic-iit/matio-cpp/files/5879666/quick_test.txt)
compiled with the following command:

    g++ quick_test.cpp -lmatioCpp -o quick_test

Aside, I have the same output as yours, CHAR and UTF8. Catch2 can be concerned?
logs: [additional_logs.txt](https://github.com/dic-iit/matio-cpp/files/5879675/additional_logs.txt)

**Comment by S-Dafarra** [comment]
> Okay, it may be linked to the test? I tried to reproduce it outside of the test framework and I encountered no error.
> With the following code:
> [quick_test.txt](https://github.com/dic-iit/matio-cpp/files/5879666/quick_test.txt)
> compiled with the following command:
> 
> ```
> g++ quick_test.cpp -lmatioCpp -o quick_test
> ```
> 
> Aside, I have the same output as yours, CHAR and UTF8. Catch2 can be concerned?
> logs: [additional_logs.txt](https://github.com/dic-iit/matio-cpp/files/5879675/additional_logs.txt)

Ah, good point. To check that, can you try to substitute https://github.com/dic-iit/matio-cpp/blob/ef999d85b8c2a5cf7f3406ffed951437536e5d40/test/FileUnitTest.cpp#L161
with 
```
    bool ok = string() == "test";
    REQUIRE(ok);
```
Maybe, naming that variable ``string`` was a bit of an unhappy choice :sweat_smile:.
With Catch we usually have issues when comparing iterators in the ``REQUIRE`` command because of its own internal conversion mechanism to a string.

**Comment by traversaro** [comment]
I added a CI job using conda-forge and hence matio 1.15.19 and the tests are passing fine https://github.com/dic-iit/matio-cpp/pull/29 . Probably it could make sense to avoid altogether to use `string` as a variable name and change the name of that variable?

**Comment by S-Dafarra** [comment]
> I added a CI job using conda-forge and hence matio 1.15.19 and the tests are passing fine #29 . Probably it could make sense to avoid altogether to use `string` as a variable name and change the name of that variable?

Awesome! Yes, if https://github.com/dic-iit/matio-cpp/issues/28#issuecomment-768210022 fixes the problem I will open a PR renaming that variable.

**Comment by traversaro** [comment]
I just realized that it should not be difficult to also add a GitHub Actions job for archlinux, something like: 
~~~
name: C++ CI Workflow with conda-forge dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.docker_image }}@${{ matrix.build_type }}]'
    # This is jut the docker host, the real os is specified in docker_image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Release]
        docker_image: "archlinux:latest"
      fail-fast: false
    
    container:
      image: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: |
        # Not really sure about this part
        pacman -S cmake gcc ninja catch2 libmatio
        
    - name: Configure 
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
     
    - name: Build 
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}
        
    - name: Test
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}

~~~

However, given that we are not big arch users, if we can verify that it is working fine without setting up a CI job that it may be complex to mantain in the future it would be great.

**Comment by S-Dafarra** [comment]
I have opened https://github.com/dic-iit/matio-cpp/pull/30. @DrasLorus, please let us know if you still encounter the issue

**Comment by xEnVrE** [comment]
> not sure about the pacman invocation, probably some arch users such as @diegoferigo or @xEnVrE can correct me

seems fine

**Comment by xEnVrE** [comment]
@traversaro I checked it again, and probably there is a missing `sudo` before the actual `pacman` invocation

**Comment by traversaro** [comment]
> 
> 
> @traversaro I checked it again, and probably there is a missing `sudo` before the actual `pacman` invocation

Thanks, I think you don't need sudo in Docker/GitHub actions, see for example https://github.com/robotology/robotology-superbuild/blob/master/.github/workflows/ci.yml#L131 .

**Comment by xEnVrE** [comment]
I was confused by the ci.yml in this repository :)

https://github.com/dic-iit/matio-cpp/blob/949f9e52487afbfb33f62f4c03051fdb9c487441/.github/workflows/ci.yml#L60-L61

**Comment by xEnVrE** [comment]
It also seems that `libmatio` is not available from `pacman`. It is however available using `AUR` (the Arch user repository) but this gets probably more complicated (I mean to use AUR within a GitHub action) than simply cloning the repository and building it from the GitHub action.

**Comment by DrasLorus** [comment]
I'm sorry for long answer time, I'm investigating ; The first test now work, I have some problems with the line 274 now: 

    matioCpp::String inputString("string", "test");
    REQUIRE(file.write(inputString));
    std::string justWritten = file.read("string").asString()();
    REQUIRE(justWritten == "test");

It fails in code and... Octave reports `uint16` for string while MATLAB reports `char` of 2 bytes (UTF-16?) but both contain [116, 101, 115, 116] which is the UTF values of 'test'. Doing `char(string)` in Octave also produce `'test'`.

It may be related to MAT file version? My libmatio defaults to mat-file v7.3, I may test with lower version.

**Comment by DrasLorus** [comment]
> It also seems that `libmatio` is not available from `pacman`. It is however available using [AUR](https://aur.archlinux.org/packages/libmatio/) (the Arch user repository) but this gets probably more complicated (I mean to use AUR within a GitHub action) than simply cloning the repository and building it from the GitHub action.

I am the maintainer of the libmatio package on the AUR. I have begin to create a PKGBUILD for Matio-Cpp that's how I encountered the issue.

Normally, to use the package from the AUR, you need `pacman -Syu base-devel --noconfirm` then clone using the AUR link, go in and do `makepkg -si` but within a docker it's a mess (makepkg cannot be run as root by design).
It may be done by installing dependancies manually (here `pacman -Syu base-devel hdf5 --noconfirm`), clonning, creating a builder account (`useradd builder`), giving it the clone (`chown builder libmatio`) and making him do the build (`su builder -c "makepkg"`) and install the package as root (`pacman -U libmatio-*`). 

Either way, I will test the version tricks and reports what I found.

**Comment by S-Dafarra** [comment]
> I'm sorry for long answer time, I'm investigating ; The first test now work, I have some problems with the line 274 now:
> 
> ```
> matioCpp::String inputString("string", "test");
> REQUIRE(file.write(inputString));
> std::string justWritten = file.read("string").asString()();
> REQUIRE(justWritten == "test");
> ```
> 
> It fails in code and... Octave reports `uint16` for string while MATLAB reports `char` of 2 bytes (UTF-16?) but both contain [116, 101, 115, 116] which is the UTF values of 'test'. Doing `char(string)` in Octave also produce `'test'`.
> 
> It may be related to MAT file version? My libmatio defaults to mat-file v7.3, I may test with lower version.

I have been thinking about this a little bit. The ``asString()`` method should print an error if the value type of the ``matvar_t`` variable is different from ``UTF8``. Maybe the problem is the ``==`` operator when used between a static string and one output by ``matio-cpp`` in a ``REQUIRE`` method. We may try the same trick also on that line. See https://github.com/dic-iit/matio-cpp/pull/30/commits/fc01523faf60347070e22c984dfbe1dd4c08a626

Btw, thanks a lot for the effort!

**Comment by DrasLorus** [comment]
ALL RIGHT!

I have tested with default file format 'MAT_FT_5' for libmatio and everything passed. So it seems that v7.3 files are not totaly supported (as today at least) from matioCpp. It is only the case for strings.

For the record, I have re-tested libmatio and some tests are failing (for ReadWrite especially :wink: ) so more related to it than to matioCpp.

Thank you for your responsiveness!

**Comment by traversaro** [comment]
@S-Dafarra what do you think, we could open an issue to track the fact that the testsuite at the moment only covers the default .mat file format and it does not test the use of different formats? Not something we need to work on now, but to avoid to forget about it.

**Comment by S-Dafarra** [comment]
Indeed, there is a bug when reading strings from v7.3 files. See https://github.com/dic-iit/matio-cpp/issues/33

I will work on fix
