### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by traversaro** [dic-iit/matio-cpp#31]
I just realized that we do not have a release for this repo, and https://github.com/robotology/robotology-superbuild/pull/596 is not complaining as no release is available at all. Can we add one? Also a minimal 0.0.1 or 0.1.0 release would be great.

**Comment by S-Dafarra** [comment]
Yes, I wanted to add something for https://github.com/dic-iit/matio-cpp/issues/32 and then we can create a release!

**Comment by S-Dafarra** [comment]
Any suggestion on the release version?

**Comment by S-Dafarra** [comment]
Here the release https://github.com/dic-iit/matio-cpp/releases/tag/v0.1.0

Closing
