### ISSUE TITLE
Run testsuite on the non-default .mat formats

### ISSUE THREAD

**Issue by traversaro** [dic-iit/matio-cpp#32]
At the moment, we are only running the test suite of the default .mat format used by matio. It could make sense to extend it to also to test other file formats, for example using Catch2 Generator feature https://github.com/catchorg/Catch2/blob/v2.13.4/docs/generators.md .

**Comment by S-Dafarra** [comment]
Indeed, this allowed me to find a first bug https://github.com/dic-iit/matio-cpp/issues/33

**Comment by S-Dafarra** [comment]
I added some tests in #30. Unfortunately, it seems that it crashes on Windows when using the 7.3 version of the .mat file. This happens only when ``matio`` is obtained via ``vcpkg``, which uses the version ``1.5.17``, while it is not failing with ``conda`` that instead uses the ``master`` version. Indeed, it seems that there were some leakages that have been fixed around a week ago: https://github.com/tbeu/matio/commit/905acda6b885b3971b75048b03aa91b2a893c98e. Despite this, the tests are working on Ubuntu and MacOs. I need to check if these tests work on Windows with the latest release (``1.5.19``).

**Comment by traversaro** [comment]
> while it is not failing with conda that instead uses the master version.

I think conda is using libmatio 1.5.19, see https://anaconda.org/conda-forge/libmatio .

**Comment by S-Dafarra** [comment]
> > while it is not failing with conda that instead uses the master version.
> 
> I think conda is using libmatio 1.5.19, see https://anaconda.org/conda-forge/libmatio .

Ah great, thanks. Then I will disable that test on Windows with a version lower than that one.

**Comment by traversaro** [comment]
> 
> 
> > > while it is not failing with conda that instead uses the master version.
> > 
> > 
> > I think conda is using libmatio 1.5.19, see https://anaconda.org/conda-forge/libmatio .
> 
> Ah great, thanks. Then I will disable that test on Windows with a version lower than that one.

Yes, I think it make sense. In the meanwhile I open a PR to update the matio version in vcpkg: https://github.com/microsoft/vcpkg/pull/15971 .
