### ISSUE TITLE
[Not an issue] AUR packages

### ISSUE THREAD

**Issue by DrasLorus** [dic-iit/matio-cpp#36]
I have  packaged matio-cpp into the AUR for archlinux users. 
It can be found as git version [libmatio-cpp-git](https://aur.archlinux.org/packages/libmatio-cpp-git/) or release [libmatio-cpp](https://aur.archlinux.org/packages/libmatio-cpp/).

Both can be built using an AUR helper or by doing:

    git clone https://aur.archlinux.org/libmatio-cpp[-git].git
    cd libmatio-cpp[-git]
    makepkg -si

It may help Archlinux users to install, manage and use matioCpp.

If you want more information, please notify me.

**Comment by S-Dafarra** [comment]
Thanks a lot @DrasLorus!
