### ISSUE TITLE
Add path/name of the file that matio-cpp failed to create

### ISSUE THREAD

**Issue by Nicogene** [dic-iit/matio-cpp#48]
Often the failure of the creation of the file is related to the specification to a folder that does not exist in your filesystem or on which you don't have the rights of write.

At this moment `matio-cpp` print this error in case of failure:
```
[ERROR][matioCpp::File::Create] Failed to open the file.
[ERROR][matioCpp::File::write] The file is not open.
```

It would be nice if it specify also the name/path of the file it tried to save like:

```
[ERROR][matioCpp::File::Create] Failed to open the file /home/icub/foo/foo.mat.
[ERROR][matioCpp::File::write] The file is not open /home/icub/foo/foo.mat.
```

**Comment by S-Dafarra** [comment]
Thanks @Nicogene for the issue. The relevant line is https://github.com/dic-iit/matio-cpp/blob/b35480814c1dbd87728a1c22c79be1dc3e906579/src/File.cpp#L191

I was also trying to understand if it is possible to check if the directory is already existing. It should be possible by extracting the path as in the example at http://www.cplusplus.com/reference/string/string/find_last_of/ and then using ``stat`` as suggested in https://stackoverflow.com/a/18101042
